### ISSUE TITLE
TypeError: Class extends value #<Object> is not a constructor or null

### ISSUE THREAD

**Issue by marishprabhu** [Daniel-Yonkov/jest-mysql#88]
**Describe the bug**
When I run to add jest-mysql to my project it is throwing the above issue.

**To Reproduce**
1. Download the attached zip file and extract.
2. In jest-mysql-config file set the database details to you
[jesttestfail.zip](https://github.com/Daniel-Yonkov/jest-mysql/files/9277376/jesttestfail.zip)
r local settings.
3. run test

**Comment by Daniel-Yonkov** [comment]
Hello @marishprabhu  - Jest made some changes in the version ^28.0.0 onwards and is not being currently supported by jest-mysql. Rolling back to version 27 should address the issue you are facing.

**Comment by marishprabhu** [comment]
Thank you.

**Comment by Daniel-Yonkov** [comment]
@marishprabhu  - The new version of jest-mysql@2.0.0 should support the latest jest version.
